version: '2'

services:
  postgres:
    image: postgres:9.5
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: 112233

  librecov:
    image: yknx4/librecov:latest
    ports:
      - "4000:4000"
    volumes:
      - ./config/local.sample.exs:/librecov/config/local.exs
