on: push

jobs:
  dependencies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: ["1.12.2"]
        otp: ["24.0"]
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout Github repo
        uses: actions/checkout@v2
      - name: Sets up an Erlang/OTP environment
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Retrieve cached dependencies
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
            priv/plts
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}-v2
      - name: Install dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p priv/plts
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix deps.compile
          mix dialyzer --plt
          mix compile

  static-code-analysis:
    needs: dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: ["1.12.2"]
        otp: ["24.0"]
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout Github repo
        uses: actions/checkout@v2
      - name: Sets up an Erlang/OTP environment
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Retrieve cached dependencies
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
            priv/plts
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}-v2
      - run: mix format --check-formatted
      - run: mix credo
      - run: mix dialyzer --no-check --ignore-exit-status

  mix-test:
    runs-on: ubuntu-latest
    needs: dependencies
    env:
      MIX_ENV: test
    strategy:
      matrix:
        elixir: ["1.12.2"]
        otp: ["24.0"]
    services:
      db:
        image: postgres:latest
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v4.8

      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout Github repo
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install NPM Packages (Global)
        run: yarn install

      - uses: c-hive/gha-yarn-cache@v2
      - name: Sets up an Erlang/OTP environment
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Retrieve cached dependencies
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
            priv/plts
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}-v2
      - run: mix coveralls.json --trace --slowest 10
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: cover/excoveralls.json
          fail_ci_if_error: true
      - name: LibreCov
        env:
          SHA: ${{github.sha}}
          BRANCH: ${{ steps.branch-name.outputs.current_branch }}
          TOKEN: ${{ secrets.OPENCOV_TOKEN }}
          COVERALLS_ENDPOINT: ${{ secrets.OPENCOV_ENDPOINT }}
        run: |
          MIX_ENV=test mix coveralls.post \
          --name github \
          --build "$GITHUB_RUN_ID" \
          --sha "$SHA" \
          --committer "$(git log -1 $SHA --pretty=format:'%cN')" \
          --message "$(git log -1 $SHA --pretty=format:'%s')" \
          --branch "$BRANCH" \
          --token "$TOKEN"
      - name: Codecov Staging
        continue-on-error: true
        env:
          CODECOV_URL: https://librecov-staging.herokuapp.com/
          CODECOV_TOKEN: ${{ secrets.LIBRECOV_TOKEN }}
          GITHUB_RUN_ID: "1${{ github.run_id }}"
        run: |
          yarn add codecov
          npx codecov --disable=s3